language: node_js
node_js:
  - "node"

git:
  depth: 3

branches:
  only:
  - master

script: bash ./deploy.sh

env:
  global:
    secure: "GFvVqZJ0n4iKWCVsGdWqN1xxI5jnyLGvo0xJI6M7u2Hfg8jYapnsuNrkfIuWrnRoky1wmh4XHRn6Z1l+Itfsw34txrApYrRLKiRjeY6NnRwbPYm8h3B1GdbVsEvTfPbYhFJCt6432VD3bTugl9ZEOcdyRkPho2V7xFHAH5E/0uokY
8esdM9mX6vG5GjQTXlF+4matN7olgnLeokgT5F7Bjb95CJ2DreUOLMWWnLxP0fs/B5mALiS6GNjE+uAhXhBx4TJ240NPq0G8yew51XIIaWx9If1JhwKD9fdsNZNgclq43w4Bvv5di4hwyCw0imAlkzzob8m0aevMKan7Fl91shAn1sV9+6xnJ1Yw
W/98T9/SyJv8APKwAV313REEhVluqqgFPuQPsEdIACIMhufDmjmmC2keRY5u4axxie/kVe/s1vNJUOFxhEISBBSjLTPKPrWHcMHY/L6P1Ig4BLpRnUOuFq+67aFNVZgl7t1MtK4sozEp23RjmGXPBntRUCE27PxoK6SToRZxsX7MJp8ar4ELvaUd
9jDAD2cf1jPPAkuutgP7W/FEkR/Yf0d8RaFZIsZ+hzUBF3TeLES6sGhAq7CPAba2PiIyf6pXAQ+ZZUOumlv20TYnwMetnyRjHnOBEeXW73S81FijdNNFb9dfhQMwrXR88vLzdQOu/BDFjg="
