language: node_js
node_js:
- node
git:
  depth: 3
branches:
  only:
  - master
script: bash ./deploy.sh
env:
  global:
    secure: L8pLU5h5E9HEMp0glPcPyQB7v2BSG2HBjrVl8oplJROMSeyydqvXjJNuy8C74aqeinmUVl1AFvaS6Pmg9yJINHqCiEGOUAKgmaNZK4lUHNkD+d/ot4cujvxFsWZHPVMeeA+32APlbG2e0DPkOUZyxJPWylaR8Zg6owZWNKWQia+BTrdvHSQWN4Wti/pTEEQn2WXYkfx+yWiqgEN0eeveScpLkxVbE5GnKIYkDzL9DqfGyeuLW0FIMmzA92hNFVJHsjiVaO1lQHWdXBxeQ+3tyfwSZC75eZFOv331GHVnkC1VOruG3Ar0E8g2nN9D158L+axrLB7TWNXe3yqeOD/0mwDqXi3TYS9YCbWKOFweZSrI9U8oBbfPY+qKIdPmn3YPjliTDRYzUYVeY+iKyHW804suNR3ZqogfFFmUugTcOKSp77lVuIfPUVuAL0bxsbqEK83eb44C/GVcYIdt3wCH621taNCso+yxNzODp6OOA3OMxdaYl5WJMgomLAcuY1uneJBPuvbp40aIWrGoskeUaUUY2RfAlI7IBmZhMoN4PqJ4OaA6A3u3AIzyrpVEOMlFoQs/BUuH9BYCSw6ndOK//EQ09CLbT93jLav+lkXzK0B5YjjDT96jIPgLsE0CGmPRVW5VcAXOI6PJKFiDQD2BX2GPpMysamU2A0X72tb2t98=
