language: node_js
node_js:
- node
git:
  depth: 3
branches:
  only:
  - master
script: bash ./deploy.sh
env:
  global:
    secure: "HgWkNn1hoC+kTMU/ANmFlcZHPiNvNr6NKeDqGkcN2nJnpc5CLdPPn8RAh5W1SHgutggcby9rK9sNiOIJQWmyb18Aibb0cDsq1PF30s5ABv+JT/1zE0r7tL3wnx/G1F6Hq5U4LzhP9tAsNUzo6/uIjhm/TiLzvXZ+PgR5WsQ9rKto5TQ908balxEsPHF6enuAYpuR2NFJck1CrHVIrJLen06/aiBMAQveSbJddtp340Veg8z0E8RqCCx90xQLKsPqGx3cl8VeqbZuhhJR4Y6TqdVXvgEy1h4yXpPYK+FxKwrk7MVjTgdLUj8Ig6LaozdQHhdmXgT2iiKAhCCnjros6sO+W/9XTOTuNMOM2vZ72GV0ZSeSsCqK8RGgeH26BvdzmtkXNbMAZbFUsd4/AVm6A7JAKoST8ILyJDeUOini8qpVUsCFalnXhutkpQMJ53ZDOdWgF9WaanpXAVEiFrrgLbIwTlVUT9NrIir0mDjatCm8OlVDGWt1fBjw6x1fPFAau6dNsFCj5kCx2rJw9yRTjqBjiJ3lNv8N6z9WX4mex9R18x/O51cjolZehK+h2cut9A9IfFFuAIEWbriJ1wD7wv5upuaPWjUtMT+5AwHpTfoa7dWT39IVM/Hun+TtsOV3kTluRV3ocPFDdNv3yuG0yUXVJQOwscD7NKNncn0ltfg="
