language: node_js
node_js:
  - "node"

git:
  depth: 3

branches:
  only:
  - master

script: bash ./deploy.sh

env:
  global:
    secure:  "WVSwDkviCphUCqD1l97YHDJrAPQ2kmoYf7mveaxlc1+sRh0Iq0neyGhnYS29jFsVvjrz8b3lOoQEyqB6Jg6mzijRhXil8hEaikN/o36DFTeEuOq5j5toFIqV3OnGkThUEj0PIpqhwqIjUJeLTuaGo5zhGPRueEmUh/QSHPko9szfrEDeGiFWdjErS/OCHbhvGcxathIf5vw/a4zy+cavKfd6C5Skq1YIQNUzLAUP1WfOn3HAZmYh0yuay9jfvpBIoqhvBNSNt6S8QsnI4e/rtfneDe1szse4P8DFeoHCle1rnQdjdaHeRxyNuHMLb1fKWr2y/7R3GJzR+9fOxl4+Fm9HAQa6FYoO0GTXo+bdmnHM2o72kGmf/xQ0tnSZ6Z1K4lgsvrF96mDYUk6jJmywF0aiwp1DhzWZAeZs2ITUfKkkPV8fTW6TRdoSls6TbQInw9mo7LXKPrlhUC+mKeUzOK31BZdya+uZtzUyCfK3paoIpF7QW9Uyc9kwuDoXK41c3tFhbfd6AuGUWAiqI9E09c7DzUMkgDmfPWyhzuVA2gqI+8osPVT935bTXItgTBz9JhP8IlR8CFUnEVpUXPbVCcvgGTfqGEsMRx3i7oRssqqiD69MktS8urdkQ/Y450xdEUYjsLitf6TKR5aQ2NLBpAXmIvnwfSy3YyLFLwyEssM="