jobs:
- job: build_upload
  timeoutInMinutes: 30

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    GITHUB_TOKEN: '$(github.token)'

  steps:
  - checkout: self
    clean: true
    fetchDepth: 5
  - script: |
      ls
      ./deploy.sh
    workingDirectory: '$(Build.SourcesDirectory)'
    displayName: 'Build'

